import { useState } from 'react'
import { PageHero } from './PageParts'
import contactImage from '../assets/images/contact-support.jpg'
import './Pages.css'

export default function Contact() {
  const [sent,setSent] = useState(false)
  const submit = (event) => { event.preventDefault(); setSent(true) }
  return <main className="inner-page">
    <PageHero kicker="Contact us" title="Tell us what you want to build or improve." description="Whether you need a website, ecommerce store, mobile app, CRM, ERP or long-term support, share the goal and we will help define the next practical step." points={['Initial requirement discussion is free','Clear recommendation before proposal','Suitable for new and existing systems','Direct response from our team']} image={contactImage} imageAlt="Mobile product interface" imageLabel="Your next project starts with a conversation" />
    <section className="page-section soft"><div className="page-container contact-grid"><div><div className="page-title"><div className="page-kicker">Let us talk</div><h2>Reach our team directly.</h2><p>Send an enquiry or use the details below. Please include your business type, required features and preferred timeline when possible.</p></div><div className="contact-cards"><div className="contact-card"><small>Call us</small><a href="tel:+919999107112">9999107112</a></div><div className="contact-card"><small>Email us</small><a href="mailto:info@iwebstechnology.com">info@iwebstechnology.com</a></div><div className="contact-card"><small>Website</small><a href="https://www.iwebstechnology.com/" target="_blank" rel="noreferrer">www.iwebstechnology.com ↗</a></div><div className="contact-card"><small>Location</small><strong>New Delhi, India</strong></div></div></div><form className="contact-form" onSubmit={submit}><h2>Project enquiry</h2><p>Complete the form and our team will contact you to understand the requirement.</p><div className="form-grid"><div className="field"><label htmlFor="name">Your name</label><input id="name" name="name" required placeholder="Full name" /></div><div className="field"><label htmlFor="phone">Phone number</label><input id="phone" name="phone" required inputMode="tel" placeholder="Contact number" /></div><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" required placeholder="name@company.com" /></div><div className="field"><label htmlFor="service">Service required</label><select id="service" name="service" defaultValue=""><option value="" disabled>Select a service</option><option>Website development</option><option>Ecommerce</option><option>Mobile application</option><option>CRM / ERP</option><option>Custom software</option><option>Marketing or support</option></select></div><div className="field full"><label htmlFor="message">Tell us about the requirement</label><textarea id="message" name="message" required placeholder="Business goal, important features, timeline and any existing website..." /></div><div className="field full"><button className="button button-primary" type="submit">Send project enquiry ↗</button></div></div>{sent && <p className="form-status" role="status">Thank you. The form interface is ready; connect it to your email or backend to receive submissions.</p>}</form></div></section>
  </main>
}
